# Istio istiod revision 1-29-1 — management cluster
revision: 1-29-1
revisionTags:
  - canary
  - stable
  - default

global:
  caAddress: cert-manager-istio-csr.cert-manager.svc:443
  sds:
    token:
      aud: istio-ca

meshConfig:
  trustDomain: project-3d092af6-3c65-4b1c-982.svc.id.goog
  trustDomainAliases:
    - project-3d092af6-3c65-4b1c-982.svc.id.goog

pilot:
  env:
    ENABLE_CA_SERVER: "false"
    EXTERNAL_CA: ISTIOD_RA_KUBERNETES_API
    TOKEN_AUDIENCES: istio-ca
